language: python
cache: pip
dist: xenial
python:
  - "3.6"
  - "3.7"

before_install:
  - pip install pip --upgrade

install:
  - pip install .[tests,pyam]

script:
  - pytest --cov -rfsxEX

after_success:
  - codecov
